import { createI18n } from 'vue-i18n'

export type AppLocale = 'zh-CN' | 'en-US'

const messages = {
  'zh-CN': {
    app: { tagline: '服务器集群智能管控平台' },
    auth: {
      username: '用户名', password: '密码', showPassword: '显示', hidePassword: '隐藏',
      signIn: '登 录', signingIn: '正在登录', setupReady: '已创建初始管理员账户，请使用部署时配置的凭据登录。',
      missingCredentials: '请输入用户名和密码',
    },
    nav: {
      dashboard: '看板总览', nodes: '节点管理', deploy: '批量部署', docker: 'Docker 管理',
      clusters: 'RKE2 集群', terminal: 'Web 终端', sftp: '文件管理', settings: '系统设置',
      automation: '自动化', sshKeys: '密钥管理', compare: '配置对比', audit: '审计日志',
      nodeDetail: '节点详情',
    },
    common: {
      online: '在线', offline: '离线', total: '总数', all: '全部', untrusted: '未授信',
      error: '异常', refresh: '刷新', changeLanguage: '切换语言', changeTheme: '切换主题', collapseSidebar: '折叠侧边栏', openNavigation: '打开导航菜单', closeNavigation: '关闭导航菜单', settings: '系统设置',
      signOut: '退出登录', cancel: '取消', confirm: '确定', load: '负载', collecting: '采集中...',
      noNodes: '暂无节点', nodeStatus: '节点状态', memory: '内存', disk: '磁盘',
      networkTraffic: '网络流量', nodeCount: '节点', onlineRate: '在线率', cpuCores: 'CPU核数',
      averageCpu: '平均CPU', physicalMachine: '物理机', addNode: '添加节点',
      firstNodeTitle: '从添加第一台节点开始',
      firstNodeDescription: '连接服务器后，即可查看状态、部署任务并管理 Docker。',
    },
    feature: {
      auditTitle: '审计日志', auditSubtitle: '所有 POST/PUT/DELETE 操作记录', exportMetrics: '导出指标 CSV', time: '时间', method: '方法', path: '路径', user: '用户', status: '状态', duration: '耗时',
      compareTitle: '节点配置对比', compareSubtitle: '横向对比两个节点的硬件和配置', nodeA: '节点 A', nodeB: '节点 B', compare: '对比', chooseNodesToCompare: '选择两个节点后点击对比', property: '属性', address: '地址', username: '用户', transport: '通信', system: '系统', architecture: '架构', region: '地区', cpuModel: 'CPU 型号', cpuCores: 'CPU 核数',
      sshKeysTitle: 'SSH 密钥管理', sshKeysSubtitle: '查看节点密钥指纹、轮换密钥', selectNodeForKeys: '选择左侧节点查看密钥信息', keyInfo: '密钥信息', rotateKey: '轮换密钥', rotatingKey: '轮换中...', clickRefreshForKey: '点击刷新查看密钥信息', keyLoadFailed: '获取失败', keyRotateSucceeded: '密钥轮换成功',
      filesTitle: '文件管理', filesSubtitle: '通过 SFTP 浏览和管理节点文件系统', selectNode: '选择节点...', selectNodeForFiles: '请选择一个节点以浏览文件系统', addNode: '添加节点', createFolder: '新建文件夹', uploadFile: '上传文件', emptyDirectory: '空目录', downloadFile: '下载', deleteFile: '删除', folderName: '文件夹名称', create: '创建', uploaded: '已上传: {name}', deleted: '已删除', created: '已创建', deleteFileConfirm: '确定删除 {name}？',
      terminalSearchNodes: '搜索节点...', terminalNoMatches: '无匹配节点', terminalReconnect: '重连', terminalCloseSession: '关闭 {name} 终端会话', terminalSplit: '分屏', terminalCancelSplit: '取消分屏', terminalStartFirst: '先添加节点再开始终端会话', terminalSelectNode: '选择左侧节点开始终端会话', terminalFirstDescription: '连接服务器后可直接打开 Web 终端。', terminalDescription: '支持多 Tab · 分屏 · 快捷键', terminalSearchPrompt: '搜索终端:', terminalReconnectFailed: '连接已断开，自动重连失败 ({count} 次)\n● 请检查网络后手动重连', terminalReconnectAfter: '连接断开，{seconds}秒后重连 (第{count}次)...', terminalReconnecting: '正在重连...',
      settingsTitle: '系统设置', settingsSubtitle: '外观偏好、账户与用户管理', appearance: '外观', themeMode: '主题模式', themeModeDescription: '深色 / 浅色 / 跟随系统', themeColor: '主题色', themeColorDescription: '界面强调色和整体配色', modeDark: '深色', modeLight: '浅色', modeSystem: '跟随', currentAccount: '当前账户', role: '角色', token: '令牌', systemInfo: '系统信息', backend: '后端', database: '数据库', version: '版本', userManagement: '用户管理', addUser: '添加用户', noUsers: '暂无用户', currentUser: '（你）', createdAt: '创建于 {time}', deleteUser: '删除用户', password: '密码', operatorRole: '操作员 (操作权限)', viewerRole: '观察者 (只读)', adminRole: '管理员 (完全权限)', enterUsername: '输入用户名', enterPassword: '输入密码', enterCredentials: '请填写用户名和密码', userCreated: '用户创建成功', deleteUserConfirm: '确定删除用户 {name}？',
      automationTitle: '自动化运维', automationSubtitle: '告警规则与定时任务管理', alertRules: '告警规则', scheduledTasks: '定时任务', addRule: '添加规则', addTask: '添加任务', enabled: '启用', disabled: '禁用', cooldownMinutes: '冷却 {minutes}分钟', noAlertRules: '暂无告警规则', addAlertRule: '添加告警规则', ruleName: '规则名称', alertRuleExample: '如：CPU 高负载告警', metric: '监控指标', cpuUsage: 'CPU 使用率', memoryUsage: '内存使用率', diskUsage: '磁盘使用率', nodeOffline: '节点离线', threshold: '阈值', greaterThan: '大于', lessThan: '小于', cooldown: '冷却时间(分钟)', webhookSupport: '支持 Slack/钉钉/企业微信/自定义 Webhook', noScheduledTasks: '暂无定时任务', everyInterval: '每 {interval} · {count} 个节点', nextRun: '下次: {next} · 上次: {last}', never: '从未', addScheduledTask: '添加定时任务', taskName: '任务名称', taskExample: '如：每日清理日志', executionInterval: '执行间隔', interval30s: '每 30 秒', interval5m: '每 5 分钟', interval10m: '每 10 分钟', interval30m: '每 30 分钟', interval1h: '每 1 小时', interval6h: '每 6 小时', interval12h: '每 12 小时', interval24h: '每 24 小时', targetNodes: '目标节点', scriptContent: '脚本内容', ruleCreated: '规则已创建', taskCreated: '任务已创建',
      deployTitle: '批量部署', deploySubtitle: '向多个节点批量推送脚本并实时查看执行结果', fileDistribution: '文件分发', newDeployTask: '新建任务', deployNeedsNode: '添加节点后即可创建部署任务', noDeployTasks: '暂无部署任务', nodeCount: '{count} 节点', selectTargetNodes: '选择目标节点', noNodes: '暂无节点', selectAllOnline: '全选在线', clear: '清空', selectedCount: '已选 {count} 个', taskConfiguration: '任务配置', taskExampleDeploy: '如：批量更新系统', type: '类型', shellScript: 'Shell 脚本', installPackage: '安装软件包', timeoutSeconds: '超时(秒)', concurrency: '并发数', executeDeploy: '执行部署', batchFileDistribution: '批量文件分发', remotePath: '远程路径', remotePathPlaceholder: '/tmp/filename (留空自动)', selectFile: '选择文件', distribute: '分发', taskDetail: '任务详情', createdLabel: '创建', running: '执行中...', noOutput: '无输出', executionContent: '执行内容', pending: '等待', completed: '成功', failed: '失败', cancelled: '已取消', script: '脚本', file: '文件', package: '软件包', selectAtLeastOneNode: '请选择至少一个节点', enterExecutionContent: '请输入执行内容', deployDefaultName: '部署-{timestamp}', taskCreatedExecuting: '任务已创建，正在执行', distributionComplete: '分发完成: 成功 {success}, 失败 {failed}',
      dockerSearchNodes: '搜索节点...', dockerNoMatches: '无匹配节点', dockerFirstNodeTitle: '先添加节点再管理 Docker', dockerSelectNode: '选择左侧节点管理 Docker', dockerFirstNodeDescription: '连接服务器后即可管理容器、镜像和网络。', dockerDescription: '容器 · 镜像 · Compose · 网络 · 卷', dockerInstall: '安装 Docker', dockerShowStopped: '显示已停止', dockerNoContainers: '暂无容器', dockerViewLogs: '查看日志', dockerMonitor: '资源监控', dockerOpenTerminal: '进入终端', dockerStop: '停止', dockerRestart: '重启', dockerStart: '启动', dockerDelete: '删除', dockerPullImage: '拉取镜像', dockerNoImages: '暂无镜像', dockerDeleteImage: '删除镜像', dockerComposeName: '项目名称', dockerDeploy: '部署', dockerNoNetworks: '暂无网络', dockerNoVolumes: '暂无存储卷', dockerContainers: '容器', dockerImages: '镜像', dockerNetworks: '网络', dockerVolumes: '卷', dockerContainerTerminal: '容器终端: {name}', dockerContainerLogs: '容器日志: {name}', dockerContainerMonitor: '容器监控: {name}', dockerMemoryPercent: '内存%', dockerNetworkIo: '网络 I/O', dockerDiskIo: '磁盘 I/O', dockerPull: '拉取', dockerInstallStarted: 'Docker 安装已启动', dockerDeleteConfirm: '确定删除？', dockerActionSucceeded: '操作成功', dockerDeleted: '已删除', dockerPullStarted: '已开始拉取', dockerEnterComposeName: '请输入项目名称', dockerDeployStarted: '部署已启动', dockerStopExecuted: '停止已执行', dockerConnectionError: '● 连接错误', dockerConnectionClosed: '● 连接已关闭', dockerConnectingLogs: '● 连接日志流...', dockerLogsEnded: '● 日志流结束',
      clusterSubtitle: '管理 RKE2 Kubernetes 集群的全生命周期', clusterCreate: '创建集群', clusterNodeCount: '节点数', clusterCreateFirst: '创建第一个集群', clusterCreateRke2: '创建 RKE2 集群', clusterSelectServer: '选择 Server 节点（控制平面）', clusterNoOnlineNodes: '暂无在线节点', clusterChecking: '检查中...', clusterRunPreflight: '运行前置检查', clusterSelectAgents: '选择 Agent 节点（工作节点，可选）', clusterNoOtherOnlineNodes: '暂无其他在线节点', clusterConfiguration: '集群配置', clusterName: '集群名称', clusterVersion: 'RKE2 版本', clusterLatestStable: '最新稳定版 (latest)', clusterCni: 'CNI 插件', clusterCanalDefault: 'canal (默认)', clusterProxy: '网络代理 (可选)', clusterEtcdSnapshots: 'ETCD 自动备份', clusterDetail: '集群详情', clusterStatus: '状态', clusterCreatedAt: '创建时间', clusterRefreshStatus: '刷新状态', clusterUninstall: '卸载集群', clusterWorkloads: 'K8s 工作负载', clusterRefreshList: '刷新列表', clusterResourceKind: '类型(deployment/service)', clusterResourceName: '名称', clusterDelete: '删除', clusterRefreshWorkloads: '点击刷新查看当前工作负载', clusterSave: '保存', clusterPods: 'Pod 列表', clusterRefreshPods: '点击刷新查看 Pod 列表', clusterHelm: 'Helm 管理', clusterHelmChart: 'chart 名称 (如: bitnami/nginx)', clusterHelmRepo: 'repo URL (可选)', clusterRefreshHelm: '点击刷新查看已安装的 Helm releases', clusterInstall: '安装', clusterRancherStatus: 'Rancher Manager 状态:', clusterInstalled: '已安装 ({version})', clusterNotInstalled: '未安装', clusterRancherHost: 'Rancher 访问域名 (如: rancher.example.com)', clusterInstallRancher: '安装 Rancher', clusterOverview: '概览', clusterHealthy: '健康', clusterDegraded: '降级', clusterProvisioning: '部署中', clusterPreflightFixing: '部分检查未通过，正在自动修复...', clusterPreflightFixed: '自动修复完成', clusterPreflightPassed: '前置检查全部通过', clusterCreateStarted: '集群创建任务已启动，安装过程请查看集群详情', clusterConfigSaved: '配置已保存', clusterHelmStarted: 'Helm 安装已启动', clusterRancherInstalling: '正在安装 Rancher，预计需要 3-5 分钟...', clusterRancherStarted: 'Rancher 安装任务已启动', clusterInstallFailed: '安装失败', clusterUninstallConfirm: '确定卸载集群 {name}？所有节点上的 RKE2 将被清除。', clusterUninstalling: '集群卸载中', clusterYamlSubmitted: 'YAML 已提交', clusterDeleted: '删除成功',
      nodesSubtitle: '管理所有服务器节点，配置 SSH 授信通道', nodesCsvTemplate: 'CSV模板', nodesImportCsv: '导入CSV', nodesExport: '导出', nodesSearch: '搜索名称或IP...', nodesAllStatuses: '全部状态', nodesSelected: '已选 {count} 个节点', nodesBatchTrust: '批量授信', nodesBatchHealth: '批量健康检查', nodesBatchDelete: '批量删除', nodesClearSelection: '取消选择', nodesStatus: '状态', nodesName: '名称', nodesAddress: '地址', nodesRegion: '地区', nodesUser: '用户', nodesHardware: '硬件', nodesTransport: '通信', nodesTags: '标签', nodesLastSeen: '最后在线', nodesActions: '操作', nodesTrust: '授信', nodesEdit: '编辑', nodesDelete: '删除', nodesEditNode: '编辑节点', nodesConnect: '连接', nodesVerify: '验证', nodesSave: '保存', nodesNameExample: '如 web-server-01', nodesHost: '主机', nodesHostPlaceholder: 'IP 或域名', nodesPort: '端口', nodesUsername: '用户名', nodesNewPassword: '新密码', nodesPasswordOptional: '留空则不修改密码', nodesPassword: '密码', nodesSshPasswordOptional: 'SSH 密码（可选）', nodesPrivateKey: 'SSH 私钥', nodesPrivateKeyPlaceholder: '粘贴 PEM 格式私钥（可选，用于密码认证失败时重试）', nodesTagsPlaceholder: '输入后回车', nodesVerifyConnection: '验证服务器连接', nodesVerifyDescription: '使用已保存的连接信息测试 {host}:{port}。', nodesEstablishTrust: '建立 SSH 授信', nodesTrustDescription: 'DeviceGrid 将安装并验证密钥登录，后续操作无需重复输入密码。', nodesTrustPasswordRequired: '授信需要 SSH 密码。请返回连接步骤填写密码后继续。', nodesReady: '节点已准备就绪', nodesReadyDescription: '{name} 已通过连接验证并完成 SSH 授信。', nodesConnectContinue: '连接并继续', nodesBack: '返回', nodesSaveNode: '保存节点', nodesEnterName: '请输入名称', nodesEnterHost: '请输入主机地址',
      nodesInProgress: '{label}中...',
      detailBack: '返回', detailDeploy: '部署', detailLiveMetrics: '实时监控', detailCpuUsage: 'CPU 使用率', detailMemoryUsage: '内存使用率', detailDiskUsage: '磁盘使用率', detailLoad: '负载 (1/5/15)', detailNetwork: '网络 {interface}', detailUptime: '运行时间',
      detailHardware: '硬件信息', detailUnknown: '未知', detailArchitecture: '架构', detailCpuTopology: '{sockets} 路 × {cores} 核 / {threads} 线程', detailVirtualization: '虚拟化', detailOperatingSystem: '操作系统', detailNotDetected: '未检测', detailNotInstalled: '未安装', detailTopProcesses: '资源占用 TOP 10', detailLoading: '加载中...', detailBasicInfo: '基本信息', detailStatus: '状态', detailAddress: '地址', detailUser: '用户', detailTransport: '通信', detailAuthentication: '认证', detailKey: '密钥', detailPassword: '密码', detailRegion: '地区',
      detailStreaming: '流媒体解锁', detailLastTested: '最后测试: {time}', detailChecking: '检测中...', detailStartCheck: '开始检测', detailStreamingLoading: '正在检测流媒体解锁状态（约30秒）...', detailStreamingEmpty: '点击“开始检测”检查流媒体解锁状态', detailAiAvailability: 'AI 服务可用性', detailAiLoading: '正在检测 AI 服务可用性...', detailAiEmpty: '点击“开始检测”检查 AI 服务可用性', detailConnectivity: '网络联通性', detailTesting: '测试中...', detailStartTest: '开始测试', detailConnectivityLoading: '正在测试各区域网络延迟...', detailUnavailable: '不通', detailPacketLoss: '{loss}%丢包', detailConnectivityEmpty: '点击“开始测试”检测各区域网络延迟',
      detailReturnRoute: '三网回程路由', detailRouteLoading: '正在测试三网回程路由（电信/联通/移动，约1-2分钟）...', detailRouteEmpty: '点击“开始测试”检测三网回程路由', detailRecentLogins: '最近登录', detailTimeline: '时间线', detailNodeCreated: '节点创建', detailLastOnline: '最后在线', detailKeyTrusted: '密钥授信', detailPhysicalMachine: '物理机', detailKvmVm: 'KVM 虚拟机', detailDockerContainer: 'Docker 容器', detailLxcContainer: 'LXC 容器', detailXenVm: 'Xen 虚拟机', detailUptimeDays: '{days}天 {hours}小时', detailUptimeHours: '{hours}小时 {minutes}分钟', detailUptimeMinutes: '{minutes}分钟',
    },
    roles: { admin: '管理员', operator: '操作员', viewer: '观察者' },
    confirm: { signOut: '确定要退出登录吗？' },
  },
  'en-US': {
    app: { tagline: 'Intelligent server fleet control plane' },
    auth: {
      username: 'Username', password: 'Password', showPassword: 'Show', hidePassword: 'Hide',
      signIn: 'Sign in', signingIn: 'Signing in', setupReady: 'An initial administrator account was created. Sign in with the credentials configured for this deployment.',
      missingCredentials: 'Enter a username and password',
    },
    nav: {
      dashboard: 'Dashboard', nodes: 'Nodes', deploy: 'Batch deploy', docker: 'Docker',
      clusters: 'RKE2 clusters', terminal: 'Web terminal', sftp: 'Files', settings: 'Settings',
      automation: 'Automation', sshKeys: 'SSH keys', compare: 'Configuration compare', audit: 'Audit log',
      nodeDetail: 'Node detail',
    },
    common: {
      online: 'Online', offline: 'Offline', total: 'Total', all: 'All', untrusted: 'Untrusted',
      error: 'Error', refresh: 'Refresh', changeLanguage: 'Change language', changeTheme: 'Change theme', collapseSidebar: 'Collapse sidebar', openNavigation: 'Open navigation menu', closeNavigation: 'Close navigation menu', settings: 'Settings',
      signOut: 'Sign out', cancel: 'Cancel', confirm: 'Confirm', load: 'Load', collecting: 'Collecting...',
      noNodes: 'No nodes yet', nodeStatus: 'Node status', memory: 'Memory', disk: 'Disk',
      networkTraffic: 'Network traffic', nodeCount: 'Nodes', onlineRate: 'Online rate', cpuCores: 'CPU cores',
      averageCpu: 'Average CPU', physicalMachine: 'Physical machine', addNode: 'Add node',
      firstNodeTitle: 'Add your first node to get started',
      firstNodeDescription: 'Connect a server to monitor it, run deployments, and manage Docker.',
    },
    feature: {
      auditTitle: 'Audit log', auditSubtitle: 'Records for POST, PUT, and DELETE operations', exportMetrics: 'Export metrics CSV', time: 'Time', method: 'Method', path: 'Path', user: 'User', status: 'Status', duration: 'Duration',
      compareTitle: 'Node configuration comparison', compareSubtitle: 'Compare hardware and configuration across two nodes', nodeA: 'Node A', nodeB: 'Node B', compare: 'Compare', chooseNodesToCompare: 'Choose two nodes, then compare them', property: 'Property', address: 'Address', username: 'User', transport: 'Transport', system: 'System', architecture: 'Architecture', region: 'Region', cpuModel: 'CPU model', cpuCores: 'CPU cores',
      sshKeysTitle: 'SSH key management', sshKeysSubtitle: 'View node key fingerprints and rotate keys', selectNodeForKeys: 'Select a node to view key information', keyInfo: 'Key information', rotateKey: 'Rotate key', rotatingKey: 'Rotating...', clickRefreshForKey: 'Refresh to view key information', keyLoadFailed: 'Unable to load key information', keyRotateSucceeded: 'SSH key rotated',
      filesTitle: 'File management', filesSubtitle: 'Browse and manage node files through SFTP', selectNode: 'Select node...', selectNodeForFiles: 'Select a node to browse its file system', addNode: 'Add node', createFolder: 'New folder', uploadFile: 'Upload file', emptyDirectory: 'Empty directory', downloadFile: 'Download', deleteFile: 'Delete', folderName: 'Folder name', create: 'Create', uploaded: 'Uploaded: {name}', deleted: 'Deleted', created: 'Created', deleteFileConfirm: 'Delete {name}?',
      terminalSearchNodes: 'Search nodes...', terminalNoMatches: 'No matching nodes', terminalReconnect: 'Reconnect', terminalCloseSession: 'Close {name} terminal session', terminalSplit: 'Split terminal', terminalCancelSplit: 'Exit split terminal', terminalStartFirst: 'Add a node to start a terminal session', terminalSelectNode: 'Select a node to start a terminal session', terminalFirstDescription: 'Connect a server to open a web terminal.', terminalDescription: 'Multi-tab · split panes · shortcuts', terminalSearchPrompt: 'Search terminal:', terminalReconnectFailed: 'Connection closed; automatic reconnection failed ({count} attempts)\n● Check the network and reconnect manually', terminalReconnectAfter: 'Connection closed; reconnecting in {seconds}s (attempt {count})...', terminalReconnecting: 'Reconnecting...',
      settingsTitle: 'Settings', settingsSubtitle: 'Appearance preferences, account, and user management', appearance: 'Appearance', themeMode: 'Theme mode', themeModeDescription: 'Dark / light / system', themeColor: 'Theme color', themeColorDescription: 'Interface accent and overall palette', modeDark: 'Dark', modeLight: 'Light', modeSystem: 'System', currentAccount: 'Current account', role: 'Role', token: 'Token', systemInfo: 'System information', backend: 'Backend', database: 'Database', version: 'Version', userManagement: 'User management', addUser: 'Add user', noUsers: 'No users yet', currentUser: '(you)', createdAt: 'Created {time}', deleteUser: 'Delete user', password: 'Password', operatorRole: 'Operator (can operate)', viewerRole: 'Viewer (read-only)', adminRole: 'Administrator (full access)', enterUsername: 'Enter username', enterPassword: 'Enter password', enterCredentials: 'Enter a username and password', userCreated: 'User created', deleteUserConfirm: 'Delete user {name}?',
      automationTitle: 'Automation', automationSubtitle: 'Alert rules and scheduled task management', alertRules: 'Alert rules', scheduledTasks: 'Scheduled tasks', addRule: 'Add rule', addTask: 'Add task', enabled: 'Enabled', disabled: 'Disabled', cooldownMinutes: '{minutes} minute cooldown', noAlertRules: 'No alert rules', addAlertRule: 'Add alert rule', ruleName: 'Rule name', alertRuleExample: 'For example: high CPU alert', metric: 'Metric', cpuUsage: 'CPU usage', memoryUsage: 'Memory usage', diskUsage: 'Disk usage', nodeOffline: 'Node offline', threshold: 'Threshold', greaterThan: 'Greater than', lessThan: 'Less than', cooldown: 'Cooldown (minutes)', webhookSupport: 'Supports Slack, DingTalk, WeCom, and custom webhooks', noScheduledTasks: 'No scheduled tasks', everyInterval: 'Every {interval} · {count} nodes', nextRun: 'Next: {next} · Last: {last}', never: 'Never', addScheduledTask: 'Add scheduled task', taskName: 'Task name', taskExample: 'For example: clean logs daily', executionInterval: 'Execution interval', interval30s: 'Every 30 seconds', interval5m: 'Every 5 minutes', interval10m: 'Every 10 minutes', interval30m: 'Every 30 minutes', interval1h: 'Every hour', interval6h: 'Every 6 hours', interval12h: 'Every 12 hours', interval24h: 'Every 24 hours', targetNodes: 'Target nodes', scriptContent: 'Script content', ruleCreated: 'Rule created', taskCreated: 'Task created',
      deployTitle: 'Batch deployment', deploySubtitle: 'Push scripts to multiple nodes and view execution results', fileDistribution: 'File distribution', newDeployTask: 'New task', deployNeedsNode: 'Add a node to create a deployment task', noDeployTasks: 'No deployment tasks', nodeCount: '{count} nodes', selectTargetNodes: 'Select target nodes', noNodes: 'No nodes yet', selectAllOnline: 'Select all online', clear: 'Clear', selectedCount: '{count} selected', taskConfiguration: 'Task configuration', taskExampleDeploy: 'For example: update systems', type: 'Type', shellScript: 'Shell script', installPackage: 'Install package', timeoutSeconds: 'Timeout (seconds)', concurrency: 'Concurrency', executeDeploy: 'Run deployment', batchFileDistribution: 'Batch file distribution', remotePath: 'Remote path', remotePathPlaceholder: '/tmp/filename (automatic when empty)', selectFile: 'Select file', distribute: 'Distribute', taskDetail: 'Task detail', createdLabel: 'Created', running: 'Running...', noOutput: 'No output', executionContent: 'Execution content', pending: 'Pending', completed: 'Completed', failed: 'Failed', cancelled: 'Cancelled', script: 'Script', file: 'File', package: 'Package', selectAtLeastOneNode: 'Select at least one node', enterExecutionContent: 'Enter execution content', deployDefaultName: 'Deploy-{timestamp}', taskCreatedExecuting: 'Task created and running', distributionComplete: 'Distribution complete: {success} succeeded, {failed} failed',
      dockerSearchNodes: 'Search nodes...', dockerNoMatches: 'No matching nodes', dockerFirstNodeTitle: 'Add a node before managing Docker', dockerSelectNode: 'Select a node on the left to manage Docker', dockerFirstNodeDescription: 'Connect a server to manage containers, images, and networks.', dockerDescription: 'Containers · Images · Compose · Networks · Volumes', dockerInstall: 'Install Docker', dockerShowStopped: 'Show stopped', dockerNoContainers: 'No containers', dockerViewLogs: 'View logs', dockerMonitor: 'Resource monitor', dockerOpenTerminal: 'Open terminal', dockerStop: 'Stop', dockerRestart: 'Restart', dockerStart: 'Start', dockerDelete: 'Delete', dockerPullImage: 'Pull image', dockerNoImages: 'No images', dockerDeleteImage: 'Delete image', dockerComposeName: 'Project name', dockerDeploy: 'Deploy', dockerNoNetworks: 'No networks', dockerNoVolumes: 'No volumes', dockerContainers: 'Containers', dockerImages: 'Images', dockerNetworks: 'Networks', dockerVolumes: 'Volumes', dockerContainerTerminal: 'Container terminal: {name}', dockerContainerLogs: 'Container logs: {name}', dockerContainerMonitor: 'Container monitor: {name}', dockerMemoryPercent: 'Memory %', dockerNetworkIo: 'Network I/O', dockerDiskIo: 'Disk I/O', dockerPull: 'Pull', dockerInstallStarted: 'Docker installation started', dockerDeleteConfirm: 'Delete this item?', dockerActionSucceeded: 'Action completed', dockerDeleted: 'Deleted', dockerPullStarted: 'Image pull started', dockerEnterComposeName: 'Enter a project name', dockerDeployStarted: 'Deployment started', dockerStopExecuted: 'Stop command sent', dockerConnectionError: '● Connection error', dockerConnectionClosed: '● Connection closed', dockerConnectingLogs: '● Connecting to log stream...', dockerLogsEnded: '● Log stream ended',
      clusterSubtitle: 'Manage the full RKE2 Kubernetes cluster lifecycle', clusterCreate: 'Create cluster', clusterNodeCount: 'Nodes', clusterCreateFirst: 'Create your first cluster', clusterCreateRke2: 'Create RKE2 cluster', clusterSelectServer: 'Select a Server node (control plane)', clusterNoOnlineNodes: 'No online nodes', clusterChecking: 'Checking...', clusterRunPreflight: 'Run preflight checks', clusterSelectAgents: 'Select Agent nodes (workers, optional)', clusterNoOtherOnlineNodes: 'No other online nodes', clusterConfiguration: 'Cluster configuration', clusterName: 'Cluster name', clusterVersion: 'RKE2 version', clusterLatestStable: 'Latest stable (latest)', clusterCni: 'CNI plugin', clusterCanalDefault: 'canal (default)', clusterProxy: 'Network proxy (optional)', clusterEtcdSnapshots: 'Automatic ETCD snapshots', clusterDetail: 'Cluster details', clusterStatus: 'Status', clusterCreatedAt: 'Created', clusterRefreshStatus: 'Refresh status', clusterUninstall: 'Uninstall cluster', clusterWorkloads: 'K8s workloads', clusterRefreshList: 'Refresh list', clusterResourceKind: 'Kind (deployment/service)', clusterResourceName: 'Name', clusterDelete: 'Delete', clusterRefreshWorkloads: 'Refresh to view current workloads', clusterSave: 'Save', clusterPods: 'Pods', clusterRefreshPods: 'Refresh to view pods', clusterHelm: 'Helm management', clusterHelmChart: 'Chart name (for example: bitnami/nginx)', clusterHelmRepo: 'Repository URL (optional)', clusterRefreshHelm: 'Refresh to view installed Helm releases', clusterInstall: 'Install', clusterRancherStatus: 'Rancher Manager status:', clusterInstalled: 'Installed ({version})', clusterNotInstalled: 'Not installed', clusterRancherHost: 'Rancher hostname (for example: rancher.example.com)', clusterInstallRancher: 'Install Rancher', clusterOverview: 'Overview', clusterHealthy: 'Healthy', clusterDegraded: 'Degraded', clusterProvisioning: 'Provisioning', clusterPreflightFixing: 'Some checks failed; applying automatic fixes...', clusterPreflightFixed: 'Automatic fixes completed', clusterPreflightPassed: 'All preflight checks passed', clusterCreateStarted: 'Cluster creation started. View cluster details for installation progress.', clusterConfigSaved: 'Configuration saved', clusterHelmStarted: 'Helm installation started', clusterRancherInstalling: 'Installing Rancher; this may take 3 to 5 minutes...', clusterRancherStarted: 'Rancher installation started', clusterInstallFailed: 'Installation failed', clusterUninstallConfirm: 'Uninstall cluster {name}? RKE2 will be removed from all nodes.', clusterUninstalling: 'Cluster uninstalling', clusterYamlSubmitted: 'YAML submitted', clusterDeleted: 'Deleted',
      nodesSubtitle: 'Manage server nodes and configure SSH trust', nodesCsvTemplate: 'CSV template', nodesImportCsv: 'Import CSV', nodesExport: 'Export', nodesSearch: 'Search name or IP...', nodesAllStatuses: 'All statuses', nodesSelected: '{count} nodes selected', nodesBatchTrust: 'Batch trust', nodesBatchHealth: 'Batch health check', nodesBatchDelete: 'Batch delete', nodesClearSelection: 'Clear selection', nodesStatus: 'Status', nodesName: 'Name', nodesAddress: 'Address', nodesRegion: 'Region', nodesUser: 'User', nodesHardware: 'Hardware', nodesTransport: 'Transport', nodesTags: 'Tags', nodesLastSeen: 'Last seen', nodesActions: 'Actions', nodesTrust: 'Trust', nodesEdit: 'Edit', nodesDelete: 'Delete', nodesEditNode: 'Edit node', nodesConnect: 'Connect', nodesVerify: 'Verify', nodesSave: 'Save', nodesNameExample: 'For example: web-server-01', nodesHost: 'Host', nodesHostPlaceholder: 'IP address or hostname', nodesPort: 'Port', nodesUsername: 'Username', nodesNewPassword: 'New password', nodesPasswordOptional: 'Leave empty to keep the password', nodesPassword: 'Password', nodesSshPasswordOptional: 'SSH password (optional)', nodesPrivateKey: 'SSH private key', nodesPrivateKeyPlaceholder: 'Paste a PEM private key (optional; retried if password authentication fails)', nodesTagsPlaceholder: 'Type and press Enter', nodesVerifyConnection: 'Verify server connection', nodesVerifyDescription: 'Test the saved connection to {host}:{port}.', nodesEstablishTrust: 'Establish SSH trust', nodesTrustDescription: 'DeviceGrid installs and verifies key authentication so later actions do not require a password.', nodesTrustPasswordRequired: 'SSH trust requires a password. Return to the connection step and provide one.', nodesReady: 'Node is ready', nodesReadyDescription: '{name} passed connection verification and SSH trust.', nodesConnectContinue: 'Connect and continue', nodesBack: 'Back', nodesSaveNode: 'Save node', nodesEnterName: 'Enter a name', nodesEnterHost: 'Enter a host address',
      nodesInProgress: '{label} in progress...',
      detailBack: 'Back', detailDeploy: 'Deploy', detailLiveMetrics: 'Live metrics', detailCpuUsage: 'CPU usage', detailMemoryUsage: 'Memory usage', detailDiskUsage: 'Disk usage', detailLoad: 'Load (1/5/15)', detailNetwork: 'Network {interface}', detailUptime: 'Uptime',
      detailHardware: 'Hardware information', detailUnknown: 'Unknown', detailArchitecture: 'Architecture', detailCpuTopology: '{sockets} sockets × {cores} cores / {threads} threads', detailVirtualization: 'Virtualization', detailOperatingSystem: 'Operating system', detailNotDetected: 'Not detected', detailNotInstalled: 'Not installed', detailTopProcesses: 'Top 10 resource consumers', detailLoading: 'Loading...', detailBasicInfo: 'Basic information', detailStatus: 'Status', detailAddress: 'Address', detailUser: 'User', detailTransport: 'Transport', detailAuthentication: 'Authentication', detailKey: 'Key', detailPassword: 'Password', detailRegion: 'Region',
      detailStreaming: 'Streaming availability', detailLastTested: 'Last tested: {time}', detailChecking: 'Checking...', detailStartCheck: 'Start check', detailStreamingLoading: 'Checking streaming availability (about 30 seconds)...', detailStreamingEmpty: 'Start a check to inspect streaming availability', detailAiAvailability: 'AI service availability', detailAiLoading: 'Checking AI service availability...', detailAiEmpty: 'Start a check to inspect AI service availability', detailConnectivity: 'Network connectivity', detailTesting: 'Testing...', detailStartTest: 'Start test', detailConnectivityLoading: 'Testing network latency by region...', detailUnavailable: 'Unavailable', detailPacketLoss: '{loss}% packet loss', detailConnectivityEmpty: 'Start a test to inspect network latency by region',
      detailReturnRoute: 'Return-route diagnostics', detailRouteLoading: 'Testing return routes (China Telecom, Unicom, and Mobile; about 1 to 2 minutes)...', detailRouteEmpty: 'Start a test to inspect return routes', detailRecentLogins: 'Recent logins', detailTimeline: 'Timeline', detailNodeCreated: 'Node created', detailLastOnline: 'Last online', detailKeyTrusted: 'Key trusted', detailPhysicalMachine: 'Physical machine', detailKvmVm: 'KVM virtual machine', detailDockerContainer: 'Docker container', detailLxcContainer: 'LXC container', detailXenVm: 'Xen virtual machine', detailUptimeDays: '{days} days {hours} hours', detailUptimeHours: '{hours} hours {minutes} minutes', detailUptimeMinutes: '{minutes} minutes',
    },
    roles: { admin: 'Administrator', operator: 'Operator', viewer: 'Viewer' },
    confirm: { signOut: 'Sign out of DeviceGrid?' },
  },
}

function initialLocale(): AppLocale {
  const saved = localStorage.getItem('dg_locale')
  if (saved === 'zh-CN' || saved === 'en-US') return saved
  return navigator.language.toLowerCase().startsWith('zh') ? 'zh-CN' : 'en-US'
}

export const i18n = createI18n({
  legacy: false,
  locale: initialLocale(),
  fallbackLocale: 'en-US',
  messages,
})

document.documentElement.lang = i18n.global.locale.value

export function setLocale(locale: AppLocale) {
  i18n.global.locale.value = locale
  localStorage.setItem('dg_locale', locale)
  document.documentElement.lang = locale
}
