// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: internal/agent/proto/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{0}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{1}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion  string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *PingResponse) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ExecRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Command        string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ExecChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Eof           bool                   `protobuf:"varint,4,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecChunk) Reset() {
	*x = ExecChunk{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecChunk) ProtoMessage() {}

func (x *ExecChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecChunk.ProtoReflect.Descriptor instead.
func (*ExecChunk) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ExecChunk) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *ExecChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecChunk) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemotePath    string                 `protobuf:"bytes,1,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *UploadRequest) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *UploadRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UploadRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *UploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemotePath    string                 `protobuf:"bytes,1,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *DownloadRequest) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,2,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Chunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type SystemInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	OsVersion     string                 `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Kernel        string                 `protobuf:"bytes,5,opt,name=kernel,proto3" json:"kernel,omitempty"`
	CpuCores      uint64                 `protobuf:"varint,6,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,7,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemTotal      uint64                 `protobuf:"varint,8,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"`
	MemUsed       uint64                 `protobuf:"varint,9,opt,name=mem_used,json=memUsed,proto3" json:"mem_used,omitempty"`
	DiskTotal     uint64                 `protobuf:"varint,10,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`
	DiskUsed      uint64                 `protobuf:"varint,11,opt,name=disk_used,json=diskUsed,proto3" json:"disk_used,omitempty"`
	DockerVersion string                 `protobuf:"bytes,12,opt,name=docker_version,json=dockerVersion,proto3" json:"docker_version,omitempty"`
	LoadAvg_1     float64                `protobuf:"fixed64,13,opt,name=load_avg_1,json=loadAvg1,proto3" json:"load_avg_1,omitempty"`
	Uptime        uint64                 `protobuf:"varint,14,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfoResponse) Reset() {
	*x = SystemInfoResponse{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfoResponse) ProtoMessage() {}

func (x *SystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfoResponse.ProtoReflect.Descriptor instead.
func (*SystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *SystemInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemInfoResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SystemInfoResponse) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *SystemInfoResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *SystemInfoResponse) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *SystemInfoResponse) GetCpuCores() uint64 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *SystemInfoResponse) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *SystemInfoResponse) GetMemTotal() uint64 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *SystemInfoResponse) GetMemUsed() uint64 {
	if x != nil {
		return x.MemUsed
	}
	return 0
}

func (x *SystemInfoResponse) GetDiskTotal() uint64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

func (x *SystemInfoResponse) GetDiskUsed() uint64 {
	if x != nil {
		return x.DiskUsed
	}
	return 0
}

func (x *SystemInfoResponse) GetDockerVersion() string {
	if x != nil {
		return x.DockerVersion
	}
	return ""
}

func (x *SystemInfoResponse) GetLoadAvg_1() float64 {
	if x != nil {
		return x.LoadAvg_1
	}
	return 0
}

func (x *SystemInfoResponse) GetUptime() uint64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

type PTYRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Term          string                 `protobuf:"bytes,3,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYRequest) Reset() {
	*x = PTYRequest{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYRequest) ProtoMessage() {}

func (x *PTYRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYRequest.ProtoReflect.Descriptor instead.
func (*PTYRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *PTYRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *PTYRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *PTYRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

type PTYChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        []byte                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Closed        bool                   `protobuf:"varint,3,opt,name=closed,proto3" json:"closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYChunk) Reset() {
	*x = PTYChunk{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYChunk) ProtoMessage() {}

func (x *PTYChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYChunk.ProtoReflect.Descriptor instead.
func (*PTYChunk) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *PTYChunk) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *PTYChunk) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *PTYChunk) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

type ClientMessage struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	NodeId   string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeName string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Metrics
	//	*ClientMessage_CommandResponse
	//	*ClientMessage_PtyOutput
	//	*ClientMessage_Heartbeat
	//	*ClientMessage_FileList
	//	*ClientMessage_FileData
	//	*ClientMessage_FileInfo
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ClientMessage) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ClientMessage) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetMetrics() *MetricsReport {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *ClientMessage) GetCommandResponse() *CommandResponse {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_CommandResponse); ok {
			return x.CommandResponse
		}
	}
	return nil
}

func (x *ClientMessage) GetPtyOutput() *PtyOutput {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_PtyOutput); ok {
			return x.PtyOutput
		}
	}
	return nil
}

func (x *ClientMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ClientMessage) GetFileList() *FileListResponse {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_FileList); ok {
			return x.FileList
		}
	}
	return nil
}

func (x *ClientMessage) GetFileData() *FileData {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_FileData); ok {
			return x.FileData
		}
	}
	return nil
}

func (x *ClientMessage) GetFileInfo() *FileInfoResponse {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_FileInfo); ok {
			return x.FileInfo
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Metrics struct {
	Metrics *MetricsReport `protobuf:"bytes,3,opt,name=metrics,proto3,oneof"`
}

type ClientMessage_CommandResponse struct {
	CommandResponse *CommandResponse `protobuf:"bytes,4,opt,name=command_response,json=commandResponse,proto3,oneof"`
}

type ClientMessage_PtyOutput struct {
	PtyOutput *PtyOutput `protobuf:"bytes,5,opt,name=pty_output,json=ptyOutput,proto3,oneof"`
}

type ClientMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,6,opt,name=heartbeat,proto3,oneof"`
}

type ClientMessage_FileList struct {
	FileList *FileListResponse `protobuf:"bytes,7,opt,name=file_list,json=fileList,proto3,oneof"`
}

type ClientMessage_FileData struct {
	FileData *FileData `protobuf:"bytes,8,opt,name=file_data,json=fileData,proto3,oneof"`
}

type ClientMessage_FileInfo struct {
	FileInfo *FileInfoResponse `protobuf:"bytes,9,opt,name=file_info,json=fileInfo,proto3,oneof"`
}

func (*ClientMessage_Metrics) isClientMessage_Payload() {}

func (*ClientMessage_CommandResponse) isClientMessage_Payload() {}

func (*ClientMessage_PtyOutput) isClientMessage_Payload() {}

func (*ClientMessage_Heartbeat) isClientMessage_Payload() {}

func (*ClientMessage_FileList) isClientMessage_Payload() {}

func (*ClientMessage_FileData) isClientMessage_Payload() {}

func (*ClientMessage_FileInfo) isClientMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_CommandRequest
	//	*ServerMessage_PtyInput
	//	*ServerMessage_PtyResize
	//	*ServerMessage_PtyClose
	//	*ServerMessage_FileListRequest
	//	*ServerMessage_FileUploadRequest
	//	*ServerMessage_FileDownloadRequest
	//	*ServerMessage_FileInfoRequest
	//	*ServerMessage_PtyStart
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetCommandRequest() *CommandRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_CommandRequest); ok {
			return x.CommandRequest
		}
	}
	return nil
}

func (x *ServerMessage) GetPtyInput() *PtyInput {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PtyInput); ok {
			return x.PtyInput
		}
	}
	return nil
}

func (x *ServerMessage) GetPtyResize() *PtyResize {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PtyResize); ok {
			return x.PtyResize
		}
	}
	return nil
}

func (x *ServerMessage) GetPtyClose() *PtyClose {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PtyClose); ok {
			return x.PtyClose
		}
	}
	return nil
}

func (x *ServerMessage) GetFileListRequest() *FileListRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_FileListRequest); ok {
			return x.FileListRequest
		}
	}
	return nil
}

func (x *ServerMessage) GetFileUploadRequest() *FileUploadRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_FileUploadRequest); ok {
			return x.FileUploadRequest
		}
	}
	return nil
}

func (x *ServerMessage) GetFileDownloadRequest() *FileDownloadRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_FileDownloadRequest); ok {
			return x.FileDownloadRequest
		}
	}
	return nil
}

func (x *ServerMessage) GetFileInfoRequest() *FileInfoRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_FileInfoRequest); ok {
			return x.FileInfoRequest
		}
	}
	return nil
}

func (x *ServerMessage) GetPtyStart() *PtyStart {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PtyStart); ok {
			return x.PtyStart
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_CommandRequest struct {
	CommandRequest *CommandRequest `protobuf:"bytes,1,opt,name=command_request,json=commandRequest,proto3,oneof"`
}

type ServerMessage_PtyInput struct {
	PtyInput *PtyInput `protobuf:"bytes,2,opt,name=pty_input,json=ptyInput,proto3,oneof"`
}

type ServerMessage_PtyResize struct {
	PtyResize *PtyResize `protobuf:"bytes,3,opt,name=pty_resize,json=ptyResize,proto3,oneof"`
}

type ServerMessage_PtyClose struct {
	PtyClose *PtyClose `protobuf:"bytes,4,opt,name=pty_close,json=ptyClose,proto3,oneof"`
}

type ServerMessage_FileListRequest struct {
	FileListRequest *FileListRequest `protobuf:"bytes,5,opt,name=file_list_request,json=fileListRequest,proto3,oneof"`
}

type ServerMessage_FileUploadRequest struct {
	FileUploadRequest *FileUploadRequest `protobuf:"bytes,6,opt,name=file_upload_request,json=fileUploadRequest,proto3,oneof"`
}

type ServerMessage_FileDownloadRequest struct {
	FileDownloadRequest *FileDownloadRequest `protobuf:"bytes,7,opt,name=file_download_request,json=fileDownloadRequest,proto3,oneof"`
}

type ServerMessage_FileInfoRequest struct {
	FileInfoRequest *FileInfoRequest `protobuf:"bytes,8,opt,name=file_info_request,json=fileInfoRequest,proto3,oneof"`
}

type ServerMessage_PtyStart struct {
	PtyStart *PtyStart `protobuf:"bytes,9,opt,name=pty_start,json=ptyStart,proto3,oneof"`
}

func (*ServerMessage_CommandRequest) isServerMessage_Payload() {}

func (*ServerMessage_PtyInput) isServerMessage_Payload() {}

func (*ServerMessage_PtyResize) isServerMessage_Payload() {}

func (*ServerMessage_PtyClose) isServerMessage_Payload() {}

func (*ServerMessage_FileListRequest) isServerMessage_Payload() {}

func (*ServerMessage_FileUploadRequest) isServerMessage_Payload() {}

func (*ServerMessage_FileDownloadRequest) isServerMessage_Payload() {}

func (*ServerMessage_FileInfoRequest) isServerMessage_Payload() {}

func (*ServerMessage_PtyStart) isServerMessage_Payload() {}

type PtyStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	Term          string                 `protobuf:"bytes,4,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyStart) Reset() {
	*x = PtyStart{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyStart) ProtoMessage() {}

func (x *PtyStart) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyStart.ProtoReflect.Descriptor instead.
func (*PtyStart) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *PtyStart) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PtyStart) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *PtyStart) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *PtyStart) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

type MetricsReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	CpuCores      uint64                 `protobuf:"varint,2,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	LoadAvg_1     float64                `protobuf:"fixed64,3,opt,name=load_avg_1,json=loadAvg1,proto3" json:"load_avg_1,omitempty"`
	LoadAvg_5     float64                `protobuf:"fixed64,4,opt,name=load_avg_5,json=loadAvg5,proto3" json:"load_avg_5,omitempty"`
	LoadAvg_15    float64                `protobuf:"fixed64,5,opt,name=load_avg_15,json=loadAvg15,proto3" json:"load_avg_15,omitempty"`
	MemTotal      uint64                 `protobuf:"varint,6,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"`
	MemUsed       uint64                 `protobuf:"varint,7,opt,name=mem_used,json=memUsed,proto3" json:"mem_used,omitempty"`
	SwapTotal     uint64                 `protobuf:"varint,8,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"`
	SwapUsed      uint64                 `protobuf:"varint,9,opt,name=swap_used,json=swapUsed,proto3" json:"swap_used,omitempty"`
	DiskTotal     uint64                 `protobuf:"varint,10,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`
	DiskUsed      uint64                 `protobuf:"varint,11,opt,name=disk_used,json=diskUsed,proto3" json:"disk_used,omitempty"`
	Uptime        uint64                 `protobuf:"varint,12,opt,name=uptime,proto3" json:"uptime,omitempty"`
	DockerVersion string                 `protobuf:"bytes,13,opt,name=docker_version,json=dockerVersion,proto3" json:"docker_version,omitempty"`
	Os            string                 `protobuf:"bytes,14,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,15,opt,name=arch,proto3" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsReport) Reset() {
	*x = MetricsReport{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsReport) ProtoMessage() {}

func (x *MetricsReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsReport.ProtoReflect.Descriptor instead.
func (*MetricsReport) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *MetricsReport) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *MetricsReport) GetCpuCores() uint64 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *MetricsReport) GetLoadAvg_1() float64 {
	if x != nil {
		return x.LoadAvg_1
	}
	return 0
}

func (x *MetricsReport) GetLoadAvg_5() float64 {
	if x != nil {
		return x.LoadAvg_5
	}
	return 0
}

func (x *MetricsReport) GetLoadAvg_15() float64 {
	if x != nil {
		return x.LoadAvg_15
	}
	return 0
}

func (x *MetricsReport) GetMemTotal() uint64 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *MetricsReport) GetMemUsed() uint64 {
	if x != nil {
		return x.MemUsed
	}
	return 0
}

func (x *MetricsReport) GetSwapTotal() uint64 {
	if x != nil {
		return x.SwapTotal
	}
	return 0
}

func (x *MetricsReport) GetSwapUsed() uint64 {
	if x != nil {
		return x.SwapUsed
	}
	return 0
}

func (x *MetricsReport) GetDiskTotal() uint64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

func (x *MetricsReport) GetDiskUsed() uint64 {
	if x != nil {
		return x.DiskUsed
	}
	return 0
}

func (x *MetricsReport) GetUptime() uint64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *MetricsReport) GetDockerVersion() string {
	if x != nil {
		return x.DockerVersion
	}
	return ""
}

func (x *MetricsReport) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *MetricsReport) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type CommandRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Command        string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{17}
}

func (x *CommandRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Done          bool                   `protobuf:"varint,5,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{18}
}

func (x *CommandResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type PtyOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Closed        bool                   `protobuf:"varint,3,opt,name=closed,proto3" json:"closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyOutput) Reset() {
	*x = PtyOutput{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyOutput) ProtoMessage() {}

func (x *PtyOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyOutput.ProtoReflect.Descriptor instead.
func (*PtyOutput) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{19}
}

func (x *PtyOutput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PtyOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PtyOutput) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

type PtyInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyInput) Reset() {
	*x = PtyInput{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyInput) ProtoMessage() {}

func (x *PtyInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyInput.ProtoReflect.Descriptor instead.
func (*PtyInput) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{20}
}

func (x *PtyInput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PtyInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PtyResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyResize) Reset() {
	*x = PtyResize{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyResize) ProtoMessage() {}

func (x *PtyResize) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyResize.ProtoReflect.Descriptor instead.
func (*PtyResize) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{21}
}

func (x *PtyResize) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PtyResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *PtyResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type PtyClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyClose) Reset() {
	*x = PtyClose{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyClose) ProtoMessage() {}

func (x *PtyClose) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyClose.ProtoReflect.Descriptor instead.
func (*PtyClose) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{22}
}

func (x *PtyClose) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type FileListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListRequest) Reset() {
	*x = FileListRequest{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListRequest) ProtoMessage() {}

func (x *FileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListRequest.ProtoReflect.Descriptor instead.
func (*FileListRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{23}
}

func (x *FileListRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileListRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Entries       []*FileEntry           `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListResponse) Reset() {
	*x = FileListResponse{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListResponse) ProtoMessage() {}

func (x *FileListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListResponse.ProtoReflect.Descriptor instead.
func (*FileListResponse) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{24}
}

func (x *FileListResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileListResponse) GetEntries() []*FileEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *FileListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	IsDir         bool                   `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	ModTime       int64                  `protobuf:"varint,5,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	Mode          string                 `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{25}
}

func (x *FileEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileEntry) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

func (x *FileEntry) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type FileUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RemotePath    string                 `protobuf:"bytes,2,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Mode          uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadRequest) Reset() {
	*x = FileUploadRequest{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadRequest) ProtoMessage() {}

func (x *FileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadRequest.ProtoReflect.Descriptor instead.
func (*FileUploadRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{26}
}

func (x *FileUploadRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileUploadRequest) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *FileUploadRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileUploadRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type FileDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RemotePath    string                 `protobuf:"bytes,2,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownloadRequest) Reset() {
	*x = FileDownloadRequest{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadRequest) ProtoMessage() {}

func (x *FileDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadRequest.ProtoReflect.Descriptor instead.
func (*FileDownloadRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{27}
}

func (x *FileDownloadRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileDownloadRequest) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

type FileData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,3,opt,name=eof,proto3" json:"eof,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileData) Reset() {
	*x = FileData{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileData) ProtoMessage() {}

func (x *FileData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileData.ProtoReflect.Descriptor instead.
func (*FileData) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{28}
}

func (x *FileData) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileData) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

func (x *FileData) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfoRequest) Reset() {
	*x = FileInfoRequest{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfoRequest) ProtoMessage() {}

func (x *FileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfoRequest.ProtoReflect.Descriptor instead.
func (*FileInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{29}
}

func (x *FileInfoRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileInfoRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	IsDir         bool                   `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfoResponse) Reset() {
	*x = FileInfoResponse{}
	mi := &file_internal_agent_proto_agent_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfoResponse) ProtoMessage() {}

func (x *FileInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_proto_agent_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfoResponse.ProtoReflect.Descriptor instead.
func (*FileInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_agent_proto_agent_proto_rawDescGZIP(), []int{30}
}

func (x *FileInfoResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileInfoResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *FileInfoResponse) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileInfoResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_agent_proto_agent_proto protoreflect.FileDescriptor

const file_internal_agent_proto_agent_proto_rawDesc = "" +
	"\n" +
	" internal/agent/proto/agent.proto\x12\x05agent\"\a\n" +
	"\x05Empty\"\r\n" +
	"\vPingRequest\"Q\n" +
	"\fPingResponse\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"P\n" +
	"\vExecRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\rR\x0etimeoutSeconds\"f\n" +
	"\tExecChunk\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x10\n" +
	"\x03eof\x18\x04 \x01(\bR\x03eof\"^\n" +
	"\rUploadRequest\x12\x1f\n" +
	"\vremote_path\x18\x01 \x01(\tR\n" +
	"remotePath\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\"@\n" +
	"\x0eUploadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"2\n" +
	"\x0fDownloadRequest\x12\x1f\n" +
	"\vremote_path\x18\x01 \x01(\tR\n" +
	"remotePath\"-\n" +
	"\x05Chunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x02 \x01(\bR\x03eof\"\x96\x03\n" +
	"\x12SystemInfoResponse\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x03 \x01(\tR\tosVersion\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x16\n" +
	"\x06kernel\x18\x05 \x01(\tR\x06kernel\x12\x1b\n" +
	"\tcpu_cores\x18\x06 \x01(\x04R\bcpuCores\x12\x1b\n" +
	"\tcpu_usage\x18\a \x01(\x01R\bcpuUsage\x12\x1b\n" +
	"\tmem_total\x18\b \x01(\x04R\bmemTotal\x12\x19\n" +
	"\bmem_used\x18\t \x01(\x04R\amemUsed\x12\x1d\n" +
	"\n" +
	"disk_total\x18\n" +
	" \x01(\x04R\tdiskTotal\x12\x1b\n" +
	"\tdisk_used\x18\v \x01(\x04R\bdiskUsed\x12%\n" +
	"\x0edocker_version\x18\f \x01(\tR\rdockerVersion\x12\x1c\n" +
	"\n" +
	"load_avg_1\x18\r \x01(\x01R\bloadAvg1\x12\x16\n" +
	"\x06uptime\x18\x0e \x01(\x04R\x06uptime\"H\n" +
	"\n" +
	"PTYRequest\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\x12\x12\n" +
	"\x04term\x18\x03 \x01(\tR\x04term\"R\n" +
	"\bPTYChunk\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\fR\x06stderr\x12\x16\n" +
	"\x06closed\x18\x03 \x01(\bR\x06closed\"\xcc\x03\n" +
	"\rClientMessage\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x120\n" +
	"\ametrics\x18\x03 \x01(\v2\x14.agent.MetricsReportH\x00R\ametrics\x12C\n" +
	"\x10command_response\x18\x04 \x01(\v2\x16.agent.CommandResponseH\x00R\x0fcommandResponse\x121\n" +
	"\n" +
	"pty_output\x18\x05 \x01(\v2\x10.agent.PtyOutputH\x00R\tptyOutput\x120\n" +
	"\theartbeat\x18\x06 \x01(\v2\x10.agent.HeartbeatH\x00R\theartbeat\x126\n" +
	"\tfile_list\x18\a \x01(\v2\x17.agent.FileListResponseH\x00R\bfileList\x12.\n" +
	"\tfile_data\x18\b \x01(\v2\x0f.agent.FileDataH\x00R\bfileData\x126\n" +
	"\tfile_info\x18\t \x01(\v2\x17.agent.FileInfoResponseH\x00R\bfileInfoB\t\n" +
	"\apayload\"\xc9\x04\n" +
	"\rServerMessage\x12@\n" +
	"\x0fcommand_request\x18\x01 \x01(\v2\x15.agent.CommandRequestH\x00R\x0ecommandRequest\x12.\n" +
	"\tpty_input\x18\x02 \x01(\v2\x0f.agent.PtyInputH\x00R\bptyInput\x121\n" +
	"\n" +
	"pty_resize\x18\x03 \x01(\v2\x10.agent.PtyResizeH\x00R\tptyResize\x12.\n" +
	"\tpty_close\x18\x04 \x01(\v2\x0f.agent.PtyCloseH\x00R\bptyClose\x12D\n" +
	"\x11file_list_request\x18\x05 \x01(\v2\x16.agent.FileListRequestH\x00R\x0ffileListRequest\x12J\n" +
	"\x13file_upload_request\x18\x06 \x01(\v2\x18.agent.FileUploadRequestH\x00R\x11fileUploadRequest\x12P\n" +
	"\x15file_download_request\x18\a \x01(\v2\x1a.agent.FileDownloadRequestH\x00R\x13fileDownloadRequest\x12D\n" +
	"\x11file_info_request\x18\b \x01(\v2\x16.agent.FileInfoRequestH\x00R\x0ffileInfoRequest\x12.\n" +
	"\tpty_start\x18\t \x01(\v2\x0f.agent.PtyStartH\x00R\bptyStartB\t\n" +
	"\apayload\"e\n" +
	"\bPtyStart\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\x12\x12\n" +
	"\x04term\x18\x04 \x01(\tR\x04term\"\xb8\x03\n" +
	"\rMetricsReport\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12\x1b\n" +
	"\tcpu_cores\x18\x02 \x01(\x04R\bcpuCores\x12\x1c\n" +
	"\n" +
	"load_avg_1\x18\x03 \x01(\x01R\bloadAvg1\x12\x1c\n" +
	"\n" +
	"load_avg_5\x18\x04 \x01(\x01R\bloadAvg5\x12\x1e\n" +
	"\vload_avg_15\x18\x05 \x01(\x01R\tloadAvg15\x12\x1b\n" +
	"\tmem_total\x18\x06 \x01(\x04R\bmemTotal\x12\x19\n" +
	"\bmem_used\x18\a \x01(\x04R\amemUsed\x12\x1d\n" +
	"\n" +
	"swap_total\x18\b \x01(\x04R\tswapTotal\x12\x1b\n" +
	"\tswap_used\x18\t \x01(\x04R\bswapUsed\x12\x1d\n" +
	"\n" +
	"disk_total\x18\n" +
	" \x01(\x04R\tdiskTotal\x12\x1b\n" +
	"\tdisk_used\x18\v \x01(\x04R\bdiskUsed\x12\x16\n" +
	"\x06uptime\x18\f \x01(\x04R\x06uptime\x12%\n" +
	"\x0edocker_version\x18\r \x01(\tR\rdockerVersion\x12\x0e\n" +
	"\x02os\x18\x0e \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x0f \x01(\tR\x04arch\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"r\n" +
	"\x0eCommandRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\rR\x0etimeoutSeconds\"\x91\x01\n" +
	"\x0fCommandResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x12\n" +
	"\x04done\x18\x05 \x01(\bR\x04done\"V\n" +
	"\tPtyOutput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06closed\x18\x03 \x01(\bR\x06closed\"=\n" +
	"\bPtyInput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"R\n" +
	"\tPtyResize\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\")\n" +
	"\bPtyClose\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"D\n" +
	"\x0fFileListRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"s\n" +
	"\x10FileListResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12*\n" +
	"\aentries\x18\x02 \x03(\v2\x10.agent.FileEntryR\aentries\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x8d\x01\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x15\n" +
	"\x06is_dir\x18\x03 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x19\n" +
	"\bmod_time\x18\x05 \x01(\x03R\amodTime\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\tR\x04mode\"\x81\x01\n" +
	"\x11FileUploadRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vremote_path\x18\x02 \x01(\tR\n" +
	"remotePath\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\"U\n" +
	"\x13FileDownloadRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vremote_path\x18\x02 \x01(\tR\n" +
	"remotePath\"e\n" +
	"\bFileData\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eof\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"D\n" +
	"\x0fFileInfoRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x8a\x01\n" +
	"\x10FileInfoResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\x12\x15\n" +
	"\x06is_dir\x18\x03 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error2\xbe\x02\n" +
	"\fAgentService\x12/\n" +
	"\x04Ping\x12\x12.agent.PingRequest\x1a\x13.agent.PingResponse\x12.\n" +
	"\x04Exec\x12\x12.agent.ExecRequest\x1a\x10.agent.ExecChunk0\x01\x125\n" +
	"\x06Upload\x12\x14.agent.UploadRequest\x1a\x15.agent.UploadResponse\x122\n" +
	"\bDownload\x12\x16.agent.DownloadRequest\x1a\f.agent.Chunk0\x01\x125\n" +
	"\n" +
	"SystemInfo\x12\f.agent.Empty\x1a\x19.agent.SystemInfoResponse\x12+\n" +
	"\x03PTY\x12\x11.agent.PTYRequest\x1a\x0f.agent.PTYChunk0\x012J\n" +
	"\rTunnelService\x129\n" +
	"\aConnect\x12\x14.agent.ClientMessage\x1a\x14.agent.ServerMessage(\x010\x01B=Z;github.com/michael/device_grid/internal/agent/proto;agentpbb\x06proto3"

var (
	file_internal_agent_proto_agent_proto_rawDescOnce sync.Once
	file_internal_agent_proto_agent_proto_rawDescData []byte
)

func file_internal_agent_proto_agent_proto_rawDescGZIP() []byte {
	file_internal_agent_proto_agent_proto_rawDescOnce.Do(func() {
		file_internal_agent_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_agent_proto_agent_proto_rawDesc), len(file_internal_agent_proto_agent_proto_rawDesc)))
	})
	return file_internal_agent_proto_agent_proto_rawDescData
}

var file_internal_agent_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_internal_agent_proto_agent_proto_goTypes = []any{
	(*Empty)(nil),               // 0: agent.Empty
	(*PingRequest)(nil),         // 1: agent.PingRequest
	(*PingResponse)(nil),        // 2: agent.PingResponse
	(*ExecRequest)(nil),         // 3: agent.ExecRequest
	(*ExecChunk)(nil),           // 4: agent.ExecChunk
	(*UploadRequest)(nil),       // 5: agent.UploadRequest
	(*UploadResponse)(nil),      // 6: agent.UploadResponse
	(*DownloadRequest)(nil),     // 7: agent.DownloadRequest
	(*Chunk)(nil),               // 8: agent.Chunk
	(*SystemInfoResponse)(nil),  // 9: agent.SystemInfoResponse
	(*PTYRequest)(nil),          // 10: agent.PTYRequest
	(*PTYChunk)(nil),            // 11: agent.PTYChunk
	(*ClientMessage)(nil),       // 12: agent.ClientMessage
	(*ServerMessage)(nil),       // 13: agent.ServerMessage
	(*PtyStart)(nil),            // 14: agent.PtyStart
	(*MetricsReport)(nil),       // 15: agent.MetricsReport
	(*Heartbeat)(nil),           // 16: agent.Heartbeat
	(*CommandRequest)(nil),      // 17: agent.CommandRequest
	(*CommandResponse)(nil),     // 18: agent.CommandResponse
	(*PtyOutput)(nil),           // 19: agent.PtyOutput
	(*PtyInput)(nil),            // 20: agent.PtyInput
	(*PtyResize)(nil),           // 21: agent.PtyResize
	(*PtyClose)(nil),            // 22: agent.PtyClose
	(*FileListRequest)(nil),     // 23: agent.FileListRequest
	(*FileListResponse)(nil),    // 24: agent.FileListResponse
	(*FileEntry)(nil),           // 25: agent.FileEntry
	(*FileUploadRequest)(nil),   // 26: agent.FileUploadRequest
	(*FileDownloadRequest)(nil), // 27: agent.FileDownloadRequest
	(*FileData)(nil),            // 28: agent.FileData
	(*FileInfoRequest)(nil),     // 29: agent.FileInfoRequest
	(*FileInfoResponse)(nil),    // 30: agent.FileInfoResponse
}
var file_internal_agent_proto_agent_proto_depIdxs = []int32{
	15, // 0: agent.ClientMessage.metrics:type_name -> agent.MetricsReport
	18, // 1: agent.ClientMessage.command_response:type_name -> agent.CommandResponse
	19, // 2: agent.ClientMessage.pty_output:type_name -> agent.PtyOutput
	16, // 3: agent.ClientMessage.heartbeat:type_name -> agent.Heartbeat
	24, // 4: agent.ClientMessage.file_list:type_name -> agent.FileListResponse
	28, // 5: agent.ClientMessage.file_data:type_name -> agent.FileData
	30, // 6: agent.ClientMessage.file_info:type_name -> agent.FileInfoResponse
	17, // 7: agent.ServerMessage.command_request:type_name -> agent.CommandRequest
	20, // 8: agent.ServerMessage.pty_input:type_name -> agent.PtyInput
	21, // 9: agent.ServerMessage.pty_resize:type_name -> agent.PtyResize
	22, // 10: agent.ServerMessage.pty_close:type_name -> agent.PtyClose
	23, // 11: agent.ServerMessage.file_list_request:type_name -> agent.FileListRequest
	26, // 12: agent.ServerMessage.file_upload_request:type_name -> agent.FileUploadRequest
	27, // 13: agent.ServerMessage.file_download_request:type_name -> agent.FileDownloadRequest
	29, // 14: agent.ServerMessage.file_info_request:type_name -> agent.FileInfoRequest
	14, // 15: agent.ServerMessage.pty_start:type_name -> agent.PtyStart
	25, // 16: agent.FileListResponse.entries:type_name -> agent.FileEntry
	1,  // 17: agent.AgentService.Ping:input_type -> agent.PingRequest
	3,  // 18: agent.AgentService.Exec:input_type -> agent.ExecRequest
	5,  // 19: agent.AgentService.Upload:input_type -> agent.UploadRequest
	7,  // 20: agent.AgentService.Download:input_type -> agent.DownloadRequest
	0,  // 21: agent.AgentService.SystemInfo:input_type -> agent.Empty
	10, // 22: agent.AgentService.PTY:input_type -> agent.PTYRequest
	12, // 23: agent.TunnelService.Connect:input_type -> agent.ClientMessage
	2,  // 24: agent.AgentService.Ping:output_type -> agent.PingResponse
	4,  // 25: agent.AgentService.Exec:output_type -> agent.ExecChunk
	6,  // 26: agent.AgentService.Upload:output_type -> agent.UploadResponse
	8,  // 27: agent.AgentService.Download:output_type -> agent.Chunk
	9,  // 28: agent.AgentService.SystemInfo:output_type -> agent.SystemInfoResponse
	11, // 29: agent.AgentService.PTY:output_type -> agent.PTYChunk
	13, // 30: agent.TunnelService.Connect:output_type -> agent.ServerMessage
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_internal_agent_proto_agent_proto_init() }
func file_internal_agent_proto_agent_proto_init() {
	if File_internal_agent_proto_agent_proto != nil {
		return
	}
	file_internal_agent_proto_agent_proto_msgTypes[12].OneofWrappers = []any{
		(*ClientMessage_Metrics)(nil),
		(*ClientMessage_CommandResponse)(nil),
		(*ClientMessage_PtyOutput)(nil),
		(*ClientMessage_Heartbeat)(nil),
		(*ClientMessage_FileList)(nil),
		(*ClientMessage_FileData)(nil),
		(*ClientMessage_FileInfo)(nil),
	}
	file_internal_agent_proto_agent_proto_msgTypes[13].OneofWrappers = []any{
		(*ServerMessage_CommandRequest)(nil),
		(*ServerMessage_PtyInput)(nil),
		(*ServerMessage_PtyResize)(nil),
		(*ServerMessage_PtyClose)(nil),
		(*ServerMessage_FileListRequest)(nil),
		(*ServerMessage_FileUploadRequest)(nil),
		(*ServerMessage_FileDownloadRequest)(nil),
		(*ServerMessage_FileInfoRequest)(nil),
		(*ServerMessage_PtyStart)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_agent_proto_agent_proto_rawDesc), len(file_internal_agent_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_agent_proto_agent_proto_goTypes,
		DependencyIndexes: file_internal_agent_proto_agent_proto_depIdxs,
		MessageInfos:      file_internal_agent_proto_agent_proto_msgTypes,
	}.Build()
	File_internal_agent_proto_agent_proto = out.File
	file_internal_agent_proto_agent_proto_goTypes = nil
	file_internal_agent_proto_agent_proto_depIdxs = nil
}
